version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build
      - run: dotnet pack --no-build --output nupkgs
      - run: dotnet publish SportApi/SportApi.csproj --framework netcoreapp2.2 -r windows-x64 --self-contained -o publishFolder
