replicaCount: 1

image:
  repository: epitaph/sport365
  tag: 1.0.0
  pullPolicy: Always

nameOverride: 
fullnameOverride: 

metadata:
  labels: {}
  annotations: {}

podAnnotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetMemoryUtilizationPercentage: "70" 
  targetCPUUtilizationPercentage: "80"
  customs: {}

serviceAccount:
  create: true
  annotations: {}
  name: "livetv"

env:
  container: {}

deployment:
  eventSource: {}

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: 4Gi
  requests:
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

budget: {}
# minAvailable: 1