repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: bitnami
  url: https://charts.bitnami.com/bitnami

helmDefaults:
  wait: true
  force: false
  atomic: true

environments:
  default:
    values:
    - namespace: livematch
    - domain: livematch.internal

releases:
- name: redis-{{ .Values.namespace }}
  chart: bitnami/redis
  version: 10.0.1
  namespace: "{{ .Values.namespace }}"
  labels:
    service: redis
  values:
  - redis.yaml.gotmpl

- name: rabbitmq-ha-{{ .Values.namespace }}
  chart: bitnami/rabbitmq
  version: 8.7.5
  namespace: "{{ .Values.namespace }}"
  labels:
    service: rabbitmq
  values:
  - rabbitmq.yaml.gotmpl

- name: api-{{ .Values.namespace }}
  chart: api
  version: 1.0.0
  namespace: "{{ .Values.namespace }}"
  labels:
    service: api
  values:
  - api.yaml.gotmpl

- name: livetv-{{ .Values.namespace }}
  chart: livetv
  version: 1.0.0
  namespace: "{{ .Values.namespace }}"
  labels:
    service: livetv
  values:
  - livetv.yaml.gotmpl