apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmi-engine.fullname" . }}
  labels:
    {{- include "nmi-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "nmi-engine.selectorLabels" . | nindent 4 }}
